modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/Ryndrixx/cosmomine"
logoFile="cosmomine.png"
description='''
Custom veinminer for the Blockbusters Aeronautics modpack.
Hold V to veinmine. Press ` to cycle mining shapes.
Shapes: Vein, Tunnel 1x2, Tunnel 3x3, Flat 3x3, Mine Staircase, Escape Tunnel.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
